import { useEffect, useState } from 'react'
import { useScrollAnimation } from '../hooks/useScrollAnimation'

// Per-platform display metadata. The runtime status (Pass/Partial/Fail)
// and Last verified date come from /validated/last-run.json, which is
// regenerated by tests/antibot/run-local.sh on every release.
const PLATFORMS = [
  {
    key: 'reddit-composer-expand',
    label: 'Reddit composer expand',
    icon: '/validated-icons/reddit.svg',
    detail: 'CDP click expands faceplate-* composer (PointerEvent isPrimary=true check)',
    competitors: {
      Playwright: { status: 'fail', note: 'fresh profile, no logged-in session; faceplate-* PointerEvent shape check rejects synthetic clicks' },
      Puppeteer: { status: 'fail', note: 'same as Playwright + no native fiber bypass' },
      'browser-use': { status: 'fail', note: 'wraps Playwright; inherits the rejection' },
      'crawl4ai': { status: 'fail', note: 'read-only crawler, no interactive operations' },
    },
  },
  {
    key: 'reddit-comment-submit',
    label: 'Reddit comment typing',
    icon: '/validated-icons/reddit.svg',
    detail: 'type_text lands multi-paragraph text in Lexical with <p> structure preserved',
    competitors: {
      Playwright: { status: 'partial', note: 'page.type() works for the typing path but submit needs a real human gesture' },
      Puppeteer: { status: 'partial', note: 'same as Playwright' },
      'browser-use': { status: 'partial', note: 'same as Playwright' },
      'crawl4ai': { status: 'fail', note: 'no interactive operations' },
    },
  },
  {
    key: 'x-tweet-input',
    label: 'X / Twitter tweet input',
    icon: '/validated-icons/x.svg',
    detail: 'type_text lands isTrusted=true CDP keys in Lexical contenteditable',
    competitors: {
      Playwright: { status: 'partial', note: 'page.type() may land but Lexical state diff sometimes drops leading character; no real session' },
      Puppeteer: { status: 'partial', note: 'same as Playwright' },
      'browser-use': { status: 'partial', note: 'wraps Playwright' },
      'crawl4ai': { status: 'fail', note: 'no interactive operations' },
    },
  },
  {
    key: 'linkedin-feed-composer',
    label: 'LinkedIn feed composer',
    icon: '/validated-icons/linkedin.svg',
    detail: 'Click "Start a post" + type into Quill editor',
    competitors: {
      Playwright: { status: 'fail', note: 'fresh profile; LinkedIn login flow needs handling each session' },
      Puppeteer: { status: 'fail', note: 'same as Playwright' },
      'browser-use': { status: 'fail', note: 'wraps Playwright' },
      'crawl4ai': { status: 'fail', note: 'no interactive operations' },
    },
  },
  {
    key: 'facebook-feed-composer',
    label: 'Facebook feed composer',
    icon: '/validated-icons/facebook.svg',
    detail: 'Click composer trigger + type into Lexical modal',
    competitors: {
      Playwright: { status: 'fail', note: 'fresh profile; Facebook anti-bot redirects to checkpoint on new profile' },
      Puppeteer: { status: 'fail', note: 'same as Playwright' },
      'browser-use': { status: 'fail', note: 'wraps Playwright' },
      'crawl4ai': { status: 'fail', note: 'no interactive operations' },
    },
  },
  {
    key: 'instagram-input',
    label: 'Instagram React input',
    icon: '/validated-icons/instagram.svg',
    detail: 'fill_input via React-aware native value setter',
    competitors: {
      Playwright: { status: 'fail', note: 'fresh profile; no real logged-in session; React-controlled inputs ignore vanilla value assignment' },
      Puppeteer: { status: 'fail', note: 'same as Playwright' },
      'browser-use': { status: 'fail', note: 'wraps Playwright' },
      'crawl4ai': { status: 'fail', note: 'no interactive operations' },
    },
  },
  {
    key: 'radix-dialog-scoping',
    label: 'Radix portal dialog',
    icon: '/validated-icons/radixui.svg',
    detail: 'click_element(in_dialog=true) scopes uniquely to the open dialog',
    competitors: {
      Playwright: { status: 'partial', note: 'no built-in dialog scope; caller must hand-roll [role=dialog] selectors' },
      Puppeteer: { status: 'partial', note: 'same as Playwright' },
      'browser-use': { status: 'partial', note: 'wraps Playwright' },
      'crawl4ai': { status: 'fail', note: 'no interactive operations' },
    },
  },
  {
    key: 'closed-shadow-input',
    label: 'Closed shadow DOM',
    icon: '/validated-icons/webcomponentsdotorg.svg',
    detail: 'find_text pierces Stencil closed shadow roots via chrome.dom API',
    competitors: {
      Playwright: { status: 'fail', note: 'no API to reach closed shadow roots' },
      Puppeteer: { status: 'fail', note: 'no API to reach closed shadow roots' },
      'browser-use': { status: 'fail', note: 'wraps Playwright; same limitation' },
      'crawl4ai': { status: 'fail', note: 'static-HTML focus, no closed-shadow access' },
    },
  },
  {
    key: 'tiptap-silent-drop',
    label: 'TipTap / ProseMirror',
    icon: '/validated-icons/prosemirror.svg',
    detail: 'type_text lands in contenteditable; auto-recovery on silent-drop',
    competitors: {
      Playwright: { status: 'partial', note: 'page.type() works on standard editors; no recovery when stricter TipTap configs discard keys' },
      Puppeteer: { status: 'partial', note: 'same as Playwright' },
      'browser-use': { status: 'partial', note: 'wraps Playwright' },
      'crawl4ai': { status: 'fail', note: 'no interactive operations' },
    },
  },
]

const STATUS_LABEL = {
  Pass: { label: 'Working', color: 'var(--green)', dot: '#16a05a' },
  Partial: { label: 'Partial', color: '#d97706', dot: '#d97706' },
  Fail: { label: 'Not working', color: 'var(--red)', dot: '#c94020' },
}

const CompStatus = ({ status, note }) => {
  const meta = status === 'pass'
    ? { color: 'var(--green)', label: '✓ Works' }
    : status === 'partial'
      ? { color: '#d97706', label: '~ Partial' }
      : { color: 'var(--red)', label: '✗ No' }
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '0.15rem' }}>
      <span style={{ color: meta.color, fontWeight: 600, fontSize: '0.85rem' }}>{meta.label}</span>
      <span style={{ color: 'var(--muted)', fontSize: '0.75rem', lineHeight: 1.4 }}>{note}</span>
    </div>
  )
}

const COMPETITORS = ['Chromeflow', 'Playwright', 'Puppeteer', 'browser-use', 'crawl4ai']

const formatDate = (iso) => {
  if (!iso) return ''
  // YYYY-MM-DD → 25 May 2026
  const m = iso.match(/(\d{4})-(\d{2})-(\d{2})/)
  if (!m) return iso
  const months = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  return `${parseInt(m[3], 10)} ${months[parseInt(m[2], 10) - 1]} ${m[1]}`
}

export default function ValidatedPlatforms() {
  const ref = useScrollAnimation()
  const [data, setData] = useState({ platforms: [], generated_at: null })
  const [openKey, setOpenKey] = useState(null)

  useEffect(() => {
    fetch('/validated/last-run.json')
      .then((r) => r.ok ? r.json() : null)
      .then((json) => { if (json) setData(json) })
      .catch(() => { /* keep defaults */ })
  }, [])

  const byKey = Object.fromEntries((data.platforms || []).map((p) => [p.name, p]))
  const generated = data.generated_at ? formatDate(data.generated_at) : ''

  return (
    <section ref={ref} style={{
      borderTop: '1px solid var(--border)',
      padding: '5rem 0',
      background: 'var(--surface)',
    }}>
      <div className="wrap">
        <p className="fade-up" style={{
          fontFamily: 'JetBrains Mono, monospace',
          fontSize: '0.7rem', letterSpacing: '0.12em',
          textTransform: 'uppercase', color: 'var(--amber)',
          marginBottom: '0.75rem',
        }}>
          Validated platforms
        </p>
        <h2 className="fade-up delay-1" style={{
          fontSize: 'clamp(1.9rem, 3.5vw, 2.8rem)',
          fontWeight: 700, letterSpacing: '-0.025em',
          marginBottom: '0.75rem',
        }}>
          Works today, tested today.
        </h2>
        <p className="fade-up delay-1" style={{
          fontSize: '1rem', color: 'var(--muted)',
          maxWidth: 720, marginBottom: '2.5rem', lineHeight: 1.6,
        }}>
          Each row is a real procedure we ran against the live platform.
          The status reflects the result of the last release-gate
          validation; click the chevron to see how Playwright,
          Puppeteer, browser-use, and crawl4ai handle the same task.
        </p>

        <div className="fade-up delay-2" style={{
          background: 'var(--surface)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius-lg)',
          boxShadow: 'var(--shadow)',
          overflow: 'hidden',
        }}>
          {PLATFORMS.map((p, idx) => {
            const live = byKey[p.key]
            const status = live?.status || 'Pass'
            const meta = STATUS_LABEL[status] || STATUS_LABEL.Pass
            const isOpen = openKey === p.key
            const last = formatDate(live?.last_verified)
            return (
              <div key={p.key} style={{
                borderBottom: idx === PLATFORMS.length - 1 ? 'none' : '1px solid var(--border)',
              }}>
                <button
                  onClick={() => setOpenKey(isOpen ? null : p.key)}
                  style={{
                    width: '100%',
                    background: 'transparent',
                    border: 'none',
                    cursor: 'pointer',
                    display: 'grid',
                    gridTemplateColumns: '48px 1fr auto 120px 28px',
                    gap: '1rem',
                    alignItems: 'center',
                    padding: '1.1rem 1.25rem',
                    textAlign: 'left',
                  }}
                  aria-expanded={isOpen}
                >
                  <img src={p.icon} alt="" style={{
                    width: 32, height: 32,
                    objectFit: 'contain',
                  }} />
                  <div>
                    <div style={{
                      fontSize: '1rem', fontWeight: 600,
                      color: 'var(--text)', marginBottom: '0.2rem',
                    }}>{p.label}</div>
                    <div style={{
                      fontSize: '0.8rem', color: 'var(--muted)',
                      lineHeight: 1.4,
                    }}>{p.detail}</div>
                  </div>
                  <div style={{
                    display: 'flex', alignItems: 'center', gap: '0.5rem',
                  }}>
                    <span style={{
                      width: 9, height: 9, borderRadius: '50%',
                      background: meta.dot, display: 'inline-block',
                    }} />
                    <span style={{
                      color: meta.color, fontWeight: 600,
                      fontSize: '0.85rem',
                    }}>{meta.label}</span>
                  </div>
                  <div style={{
                    fontSize: '0.75rem', color: 'var(--muted)',
                    textAlign: 'right',
                  }}>
                    {last ? `as of ${last}` : ''}
                  </div>
                  <span style={{
                    display: 'inline-block',
                    transition: 'transform 0.2s ease',
                    transform: isOpen ? 'rotate(90deg)' : 'rotate(0deg)',
                    color: 'var(--muted)',
                    fontSize: '1rem',
                  }}>›</span>
                </button>

                {isOpen && (
                  <div style={{
                    padding: '0 1.25rem 1.5rem',
                    background: 'var(--surface-2)',
                  }}>
                    <div style={{
                      fontSize: '0.7rem',
                      letterSpacing: '0.1em',
                      textTransform: 'uppercase',
                      color: 'var(--muted)',
                      paddingTop: '1rem',
                      paddingBottom: '0.5rem',
                      fontWeight: 600,
                    }}>How others handle this</div>
                    <div style={{
                      display: 'grid',
                      gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
                      gap: '1rem',
                    }}>
                      <div style={{
                        padding: '0.85rem 1rem',
                        background: 'var(--amber-glow)',
                        border: '1px solid var(--amber)',
                        borderRadius: 'var(--radius)',
                      }}>
                        <div style={{
                          fontSize: '0.85rem',
                          fontWeight: 700,
                          color: 'var(--amber)',
                          marginBottom: '0.35rem',
                        }}>Chromeflow</div>
                        <CompStatus status={status.toLowerCase()} note={live?.validated || p.detail} />
                      </div>
                      {Object.entries(p.competitors).map(([name, info]) => (
                        <div key={name} style={{
                          padding: '0.85rem 1rem',
                          background: 'var(--surface)',
                          border: '1px solid var(--border)',
                          borderRadius: 'var(--radius)',
                        }}>
                          <div style={{
                            fontSize: '0.85rem',
                            fontWeight: 700,
                            color: 'var(--text)',
                            marginBottom: '0.35rem',
                          }}>{name}</div>
                          <CompStatus status={info.status} note={info.note} />
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>

        <p style={{
          fontSize: '0.85rem',
          color: 'var(--muted)',
          marginTop: '1.5rem',
          textAlign: 'center',
          lineHeight: 1.6,
        }}>
          {generated
            ? `Last release-gate run: ${generated}. `
            : ''}
          Read the per-platform procedures at{' '}
          <a href="/validated" style={{ color: 'var(--amber)', textDecoration: 'underline' }}>
            chromeflow.run/validated
          </a>
          {' '}or in the{' '}
          <a href="https://gitlab.com/NeoDrew/chromeflow/-/tree/main/tests/antibot" style={{ color: 'var(--amber)', textDecoration: 'underline' }}>
            tests/antibot/
          </a>
          {' '}directory.
        </p>
      </div>
    </section>
  )
}
